packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  react: '19.2.4'
  react-dom: '19.2.4'
  next: '^16.1.6'
  '@types/react': '19.2.14'
  '@types/react-dom': '19.2.3'
  '@types/node': '^25.3.0'
  typescript: '5.9.3'
  eslint: '^9.39.3'
  lucide-react: '^0.575.0'
  clsx: '^2.1.1'
  class-variance-authority: '^0.7.1'
  tailwind-merge: '^3.5.0'
  zod: '^4.3.6'
  '@supabase/ssr': '^0.8.0'
  '@supabase/supabase-js': '^2.97.0'
  '@tanstack/react-query': '^5.90.21'
  '@tanstack/react-table': '^8.21.3'
  '@faker-js/faker': '^10.3.0'
  jest: '^30.2.0'
  '@swc/jest': '^0.2.39'
  '@types/jest': '^30.0.0'
  jest-environment-jsdom: '^30.2.0'
  tailwindcss: '^4.2.0'
  postcss: '^8.5.6'
  tailwindcss-animate: '^1.0.7'
