packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  react: "19.2.3"
  react-dom: "19.2.3"
  next: "^16.1.6"
  "@types/react": "19.2.7"
  "@types/react-dom": "19.2.3"
  "@types/node": "^22.19.11"
  typescript: "5.9.3"
  eslint: "^9.39.3"
  lucide-react: "^0.474.0"
  clsx: "^2.1.1"
  class-variance-authority: "^0.7.1"
  tailwind-merge: "^3.5.0"
  zod: "^3.25.76"
  "@supabase/ssr": "^0.5.2"
  "@supabase/supabase-js": "^2.97.0"
  "@tanstack/react-query": "^5.90.21"
  "@tanstack/react-table": "^8.21.3"
  "@faker-js/faker": "^9.9.0"
  jest: "^29.7.0"
  "@swc/jest": "^0.2.39"
  "@types/jest": "^29.5.14"
  jest-environment-jsdom: "^29.7.0"
  tailwindcss: "^4.2.0"
  postcss: "^8.5.6"
  tailwindcss-animate: "^1.0.7"
